name: HACS Quality Checks

on:
  pull_request:
    branches: [dev, main]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  # Bei Push: "HACS-push-dev", bei PR zu main: "HACS-pr-123"
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.ref_name || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  hacs:
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
