name: Home Assistant Quality Checks

on:
  pull_request:
    branches: [dev, main]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  # Bei Push: "HASS-push-dev", bei PR zu main: "HASS-pr-123"
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.ref_name || github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  hass:
    name: HASS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
